### ISSUE TITLE
Should the pin be updated if the underlying spec file changes?

### ISSUE THREAD

**Issue by simonjbeaumont** [xenserver/planex#187]
At present, the dependencies generated don't do this.

**Comment by simonjbeaumont** [comment]
Just placeholder-ing this thought while I'm working on something else.

**Comment by simonjbeaumont** [comment]
@euanh what do you think?

**Comment by euanh** [comment]
Yes, this would be good.  I ran into this problem originally because I had pinned to a later version of planex which added and removed some files, so I had to update the underlying spec file to match the new package contents.   Since it was not updated automatically, I had to unpin and repin (or possibly touch just the right files), which seemed ugly.
